config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, generate_new_password, activate_new_user

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/genpassword/', generate_new_password, name='generate_new_password'),
    path('activate/<int:pk>/', activate_new_user, name='activate_new_user')
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='Email')

    phone = models.CharField(max_length=25, verbose_name='Телефон')
    avatar = models.ImageField(upload_to='users/', verbose_name='аватар', blank=True, null=True)
    country = models.CharField(max_length=100, verbose_name='Страна')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.core.mail import send_mail

from config import settings
from users.models import User


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')

    def save(self, commit=True):

        user = super().save()
        send_mail(subject='Активация',
                  message=f'Для активации профиля пройдите по ссылке - http://127.0.0.1:8000/users/activate/{user.id}/',
                  from_email=settings.EMAIL_HOST_USER,
                  recipient_list=[user.email])
        user.is_active = False
        user.save()
        return user


class UserProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('phone', 'email', 'avatar', 'country')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()

users/views.py
from django.contrib.auth import get_user_model
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView
from config import settings
from users.forms import UserRegisterForm, UserProfileForm
from users.models import User


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')


class ProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


def generate_new_password(request):
    new_password = User.objects.make_random_password(length=10)
    request.user.set_password(new_password)
    send_mail(subject='Вы сменили пароль',
              message=f'Ваш новый пароль - {new_password}',
              from_email=settings.EMAIL_HOST_USER,
              recipient_list=[request.user.email])
    request.user.save()
    return redirect(reverse('catalog:home'))


def activate_new_user(request, pk):
    user = get_user_model()
    user_for_activate = user.objects.get(id=pk)
    user_for_activate.is_active = True
    user_for_activate.save()
    return render(request, 'users/activate_user.html')

users/templates/users/activate_user.html
{% extends 'catalog/base.html' %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
    <div class="col-6">
        <div class="card">
            <h2>Поздравляем, вы успешно активировались на нашей платформе</h2>
        </div>
    </div>
    </form>


{% endblock %}

users/templates/users/login.html
{% extends 'catalog/base.html' %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">
                    Авторизация пользователя
                </h3>
            </div>
            <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn-success">Войти</button>
            </div>
            <div class="card-footer"></div>
        </div>
    </div>
    </form>


{% endblock %}

users/templates/users/register.html
{% extends 'catalog/base.html' %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">
                    Регистрация пользователя
                </h3>
            </div>
            <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn-success">Войти</button>
            </div>
            <div class="card-footer"></div>
        </div>
    </div>
    </form>
{% endblock %}

users/templates/users/user_form.html
{% extends 'catalog/base.html' %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">
                    Редактирование профиля пользователя
                </h3>
            </div>
            <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn-success">Сохранить</button>
            </div>
            <div class="card-footer">
                <a href="{% url 'users:generate_new_password' %}" class="btn btn-danger">Сгенерировать пароль</a>
            </div>
        </div>
    </div>
    </form>
{% endblock %}