catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.apps import CatalogConfig
from catalog.views import contacts, ProductsDetailView, ProductListView, BlogList, BlogDetailView, BlogCreatePost, \
    BlogUpdatePost, BlogDeletePost, ProductCreateView, ProductUpdateView, ProductDeleteView, VersionListView, \
    ProductUpdateViewModerator, categories_list

app_name = CatalogConfig.name

urlpatterns = [
    path('', cache_page(60)(ProductListView.as_view()), name='home'),
    path('contacts/', contacts, name='contacts'),
    path('product/<int:pk>/', cache_page(60)(ProductsDetailView.as_view()), name='product'),
    path('blog/', BlogList.as_view(), name='blog'),
    path('blog/<slug:slug>/', BlogDetailView.as_view(), name='blog_post'),
    path('create_post/', BlogCreatePost.as_view(), name='create_post'),
    path('update_post/<slug:slug>/', BlogUpdatePost.as_view(), name='update_post'),
    path('delete_post/<slug:slug>/', BlogDeletePost.as_view(), name='delete_post'),
    path('create/', ProductCreateView.as_view(), name='create_product'),
    path('update/<int:pk>/', ProductUpdateView.as_view(), name='update_product'),
    path('update/<int:pk>/', ProductUpdateView.as_view(), name='update_product'),
    path('update/<int:pk>/moderator', ProductUpdateViewModerator.as_view(), name='update_moderator'),
    path('delete/<int:pk>/', ProductDeleteView.as_view(), name='delete_product'),
    path('versions/<int:pk>', VersionListView.as_view(), name='version'),
    path('categories/', categories_list, name='categories')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, generate_new_password, activate_new_user

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/genpassword/', generate_new_password, name='generate_new_password'),
    path('activate/<int:pk>/', activate_new_user, name='activate_new_user')
]

catalog/models.py
from django.db import models
from django_resized import ResizedImageField
from slugify import slugify

from config import settings


class Product(models.Model):
    title = models.CharField(max_length=50, verbose_name='Название')
    description = models.TextField(blank=True, null=True, verbose_name='Описание')
    image = ResizedImageField(upload_to='products/', blank=True, null=True, verbose_name='Изображение')
    category = models.ForeignKey('catalog.Category', on_delete=models.SET_NULL, null=True, verbose_name='Категория')
    price = models.IntegerField(verbose_name='Цена')
    creation_date = models.DateTimeField(auto_now_add=True)
    modification_date = models.DateTimeField(auto_now=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, blank=True, null=True)
    is_published = models.BooleanField(default=False, verbose_name='Статус публикации')

    def __str__(self):
        return f'{self.title} {self.price}'

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        permissions = [('сan_change_description', 'can change description'),
                       ('сan_change_category', 'can change category'),
                       ('сan_change_is_published', 'can change is_published'),
                       ('сan_view_price', 'can view price')]


class Category(models.Model):
    title = models.CharField(max_length=50, verbose_name='Название')
    description = models.TextField(blank=True, null=True, verbose_name='Описание')

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Blog(models.Model):
    title = models.CharField(max_length=50, verbose_name='Название')
    slug = models.SlugField(max_length=50, verbose_name='Slug')
    content = models.TextField(verbose_name='Содержимое')
    image = models.ImageField(upload_to='products/', blank=True, null=True, verbose_name='Изображение')
    created_at = models.DateTimeField(auto_now_add=True)
    is_published = models.BooleanField(default=False)
    views_count = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.title} {self.created_at}'

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'


class Version(models.Model):
    product = models.ForeignKey('catalog.Product', on_delete=models.CASCADE, verbose_name='Продукт')
    number = models.IntegerField(verbose_name='Номер версии', unique=True)
    title = models.CharField(max_length=100, verbose_name='Название версии')
    description = models.TextField(blank=True, null=True, verbose_name='Описание текущей версии')
    is_active = models.BooleanField(verbose_name='Активность')

    def __str__(self):
        return f'Продукт {self.product} версии {self.title}'

    class Meta:
        verbose_name = 'Версия'
        verbose_name_plural = 'Версии'

catalog/forms.py
from django import forms

from catalog.models import Product, Version

FORBIDDEN_WORDS = ('казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар')


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product

        fields = ('title', 'image', 'description', 'category', 'price', 'is_published')

    def clean_title(self):
        cleaned_data = self.cleaned_data['title']
        for word in FORBIDDEN_WORDS:
            if word in cleaned_data.lower():
                raise forms.ValidationError(f'Нельзя добавлять продукты с названием {word}')

        return cleaned_data

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    def clean_description(self):
        cleaned_data = self.cleaned_data['description']
        for word in FORBIDDEN_WORDS:
            if word in cleaned_data.lower():
                raise forms.ValidationError(f'Нельзя добавлять продукты у которых в описании есть слово {word}')

        return cleaned_data


class ProductFormModerator(forms.ModelForm):

    class Meta:
        model = Product
        fields = ('description', 'category', 'is_published')

    def clean_description(self):

        cleaned_data = self.cleaned_data['description']
        for word in FORBIDDEN_WORDS:
            if word in cleaned_data.lower():
                raise forms.ValidationError(f'Нельзя добавлять продукты у которых в описании есть слово {word}')

        return cleaned_data

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class VersionForm(forms.ModelForm):
    class Meta:
        model = Version
        exclude = ('product',)
#        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

catalog/views.py
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.cache import cache
from django.db import transaction
from django.forms import inlineformset_factory
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView

from catalog.models import Product, Blog, Version
from catalog.forms import ProductForm, VersionForm, ProductFormModerator
from catalog.services import get_cashed_categories_list, get_cashed_products_list


class ProductListView(ListView):
    model = Product
    context = {'title': 'Список товаров'}
    template_name = 'catalog/home.html'


def contacts(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f'{name} ({phone}): {message}')
    return render(request, 'catalog/contacts.html')


def categories_list(request):
    categories = get_cashed_categories_list()
    context = {'object_list': categories, }
    return render(request, 'catalog/categories.html', context)


class ProductsDetailView(DetailView):
    model = Product
    template_name = 'catalog/products.html'
    context_object_name = 'product'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['product'] = get_cashed_products_list(self.object.pk)
        return context_data


class BlogList(ListView):
    model = Blog
    extra_context = {'title': 'Блог'}

    def get_queryset(self):
        return Blog.objects.filter(is_published=True)


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        object = super().get_object()
        object.views_count += 1

        object.save()

        return object


class BlogCreatePost(CreateView):
    model = Blog
    fields = ('title', 'content', 'image', 'is_published')
    success_url = '/blog/'


class BlogUpdatePost(UpdateView):
    model = Blog
    fields = ('title', 'content', 'image', 'is_published')

    def get_success_url(self, *args, **kwargs):
        slug = self.kwargs['slug']
        url = reverse_lazy('catalog:blog_post', args=[slug])

        return url


class BlogDeletePost(DeleteView):
    model = Blog
    success_url = '/blog/'


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm

    success_url = reverse_lazy('catalog:home')

    def form_valid(self, form):
        product = form.save()
        product.owner = self.request.user
        product.save()
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm

    permission_required = 'catalog.сan_change_desc'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)

        ParentFormset = inlineformset_factory(self.model, Version, form=VersionForm, extra=1)

        if self.request.method == 'POST':
            formset = ParentFormset(self.request.POST, instance=self.object)
        else:
            formset = ParentFormset(instance=self.object)

        context_data['formset'] = formset
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        with transaction.atomic():
            self.object = form.save()
            if formset.is_valid():
                formset.instance = self.object
                formset.save()

        return super().form_valid(form)

    def get_success_url(self, **kwargs):
        return reverse('catalog:version', args=[self.kwargs.get('pk')])


class ProductUpdateViewModerator(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Product
    form_class = ProductFormModerator

    permission_required = 'catalog.сan_change_desc'

    def get_success_url(self, **kwargs):
        return reverse('catalog:version', args=[self.kwargs.get('pk')])


class ProductDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:home')
    permission_required = 'catalog.Can delete Продукт'


class VersionListView(ListView):
    model = Version

    def get_queryset(self, *args, **kwargs):
        product_pk = self.kwargs.get('pk')
        return Version.objects.filter(is_active=True, product_id=product_pk)

    def get_context_data(self, *args, object_list=None, **kwargs):
        product = Product.objects.get(pk=self.kwargs.get('pk'))
        context = super().get_context_data(*args, **kwargs)
        context['product_title'] = product.title
        context['pk'] = product.pk
        return context

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
</head>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href={% url 'catalog:categories' %}>Категории</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
        <a class="p-2 btn btn-outline-primary" href="/blog/">Блог</a>
        {% if user.is_authenticated %}
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:profile' %}">Профиль</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:logout' %}">Выйти</a>
        {% else %}
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:login' %}">Войти</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:register' %}">Регистрация</a>
        {% endif %}
    </nav>
</div>
<body>
{% block content%}
{% endblock %}
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023 - {% now 'Y'%}</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</body>
</html>

catalog/templates/catalog/blog_confirm_delete.html
{% extends 'catalog/base.html'%}
{% load mediapath %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Удаление записи</h1>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <form method="post">
        {% csrf_token %}
        Уверены что хотите удалить запись?
        <button type="submit" class="p-2 btn btn-outline-primary">Удалить запись</button>
    </form>
        </ul>
            <form action="/blog/{{ object.slug }}/">
                <button type="submit" class="p-2 btn btn-outline-primary">Назад</button>
            </form>
</div>
{% endblock %}

catalog/templates/catalog/blog_detail.html
{% extends 'catalog/base.html'%}
{% load mediapath %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ object.title }}</h1>
    <img src="{% mediapath object.image %}" width="200"/>
</div>

<div class="container">
    <div class="row text-center">
        <p class="lead">{{ object.content }}</p>
    </div>

    <div class="row text-center">
        <p class="lead">Опубликован: {{ object.created_at }}</p>
    </div>

    <div class="row text-center">
        <p class="lead">Просмотров: {{ object.views_count }}</p>
    </div>

<nav class="ms-5">
    {% if user.is_staff %}
        <a class="p-2 btn btn-outline-primary m-2" href="/delete_post/{{ object.slug }}">Удалить</a>
        <a class="p-2 btn btn-outline-primary m-2" href="/update_post/{{ object.slug }}/">Редактировать</a>
    {% endif %}
    <a href="{% url 'catalog:blog' %}" class="p-2 btn btn-outline-primary m-2">Назад</a>
</nav>


</div>
{% endblock %}

catalog/templates/catalog/blog_form.html
{% extends 'catalog/base.html'%}
{% load mediapath %}

{% block content %}

</div>
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Создание новой записи</h1>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="p-2 btn btn-outline-primary">Создать</button>
    </form>
</div>
{% endblock %}

catalog/templates/catalog/blog_list.html
{% extends 'catalog/base.html'%}
{% load mediapath %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ title }}</h1>
    <p class="lead">Добро пожаловать в наш блог.</p>
</div>

<div class="container">
    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
                </div>
                <div class="card-body">
                    <h5 class="card-title pricing-card-title">Дата публикации<br> {{ object.created_at }}</h5>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>Просмотров: {{ object.views_count }}</li>
                        <img src="{% mediapath object.image %}" width="200"/>

                    </ul>
                    <form action="/blog/{{ object.slug }}/">
                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Подробнее</button>
                    </form>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% if user.is_staff %}
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/create_post/">Новая запись</a>
    </nav>
{% endif %}

</div>
{% endblock %}

catalog/templates/catalog/categories.html
{% extends 'catalog/base.html'%}

{% block content %}
    {% for category in object_list %}
        <h1>Категория: {{ category }}</h1>
    {% endfor %}

{% endblock %}

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}
{% block content %}

    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Контакты</h1>
    </div>

    <div class="container">
        <div class="row text-start">
            <div class="col-lg-9 col-md-6 col-sm-12">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        <table class="table table-striped">
                            <tr>
                                <td class="w-25">Страна</td>
                                <td>USA</td>
                            </tr>
                            <tr>
                                <td class="w-25">ИНН</td>
                                <td>91-1144442</td>
                            </tr>
                            <tr>
                                <td class="w-25">Адрес</td>
                                <td>Redmond,WA,98052-6399</td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-12">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                    </div>
                    <div class="card-body">
                        <form method="post" action="" class="form-floating">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="name">Имя</label>
                                <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                       required>
                            </div>
                            <div class="mb-3">
                                <label for="phone">Телефон</label>
                                <input type="text" name="phone" class="form-control" id="phone"
                                       placeholder="Контактный телефон" required>
                            </div>
                            <div class="mb-3">
                                <label for="message">Сообщение</label>
                                <textarea type="text" name="message" class="form-control" id="message"
                                          placeholder="Сообщение" required></textarea>
                            </div>
                        </form>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                        <a href="{% url 'catalog:home' %}" class="btn btn-lg btn-block btn-outline-primary">Назад</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/home.html
{% extends 'catalog/base.html' %}
{% load mediapath %}

{% block content %}

    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Skystore</h1>
        <p class="lead">Skystore - это отличный магазин технических безделушек!</p>
    </div>

{% if request.user.is_superuser %}
    <nav class="col-2 offset-5">
        <a class="btn btn-lg btn-block btn-outline-primary mb-4" href="{% url 'catalog:create_product' %}">Новый продукт</a>
    </nav>
{% endif %}

    <div class="container">
        <div class="row text-center">
            {% for object in object_list %}
                <div class="col-3">
                    <div class="card mb-4 box-shadow">
                        <div class="card-header">
                            <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
                        </div>
                        <div class="card-body">
                            <h1 class="card-title pricing-card-title">$ {{ object.price }}</h1>
                            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                                <li>Категория: {{ object.category }}</li>
                                <li>Описание: {{ object.description|slice:':100' }}</li>
                                <img src="{% mediapath object.image %}"/>
                            </ul>
                            <a href="{% url 'catalog:product' object.pk %}" class="btn btn-lg btn-block btn-outline-primary">Подробнее</a>
                            <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

    </div>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html'%}
{% load mediapath %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Удаление продукта</h1>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <form method="post">
        {% csrf_token %}
        Уверены что хотите удалить продукт?
        <button type="submit" class="p-2 btn btn-outline-primary">Удалить продукт</button>
    </form>
            <form action="/product/{{ object.pk }}/">
                <button type="submit" class="p-2 btn btn-outline-primary">Назад</button>
            </form>
</div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}

{% block content %}
    {% if product.owner == request.user or request.user.is_superuser %}
        <form method="post" enctype="multipart/form-data">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            Добавление продукта
                        </h3>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn-success">Сохранить</button>
                    </div>
                    <div class="card-footer"></div>
                </div>
                {% if object %}
                    <div class="col-8">
                        <div class="card">
                            <div class="card-header">
                                Версии продукта
                            </div>
                            <div class="card-body">
                                <div class="formset">
                                    {{ formset.management_form }}
                                    {% for form in formset.forms %}
                                        <div class="formset_row">
                                            {% for field in form.visible_fields %}
                                                <div class="formset-col">
                                                    {% if forloop.first %}
                                                        {% for hidden in form.hidden_fields %}
                                                            {{ hidden }}
                                                        {% endfor %}
                                                    {% endif %}
                                                    {{ field.errors.as_ul }}
                                                    {% if not forloop.last %}
                                                        {{ field.label }}
                                                    {% endif %}
                                                    {{ field }}
                                                </div>
                                            {% endfor %}
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
            </div>
        </form>
    {% elif perms.catalog.сan_change_desc %}
        <form method="post" enctype="multipart/form-data">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            Добавление продукта
                        </h3>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn-success">Сохранить</button>
                    </div>
                </div>
            </div>
        </form>
    {% endif %}


{% endblock %}

catalog/templates/catalog/products.html
{% extends 'catalog/base.html' %}

{% load static %}
{% load mediapath %}


{% block content %}
    <div class="col-md-9">

        <section class="py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="row gx-4 gx-lg-5 align-items-center">
                    <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0"
                        <img src="{% mediapath object.image %}"/></div>
                    <div class="col-md-6">

                        <h1 class="display-5 fw-bolder">Название товара: {{ object.title }}</h1>
                        <div class="fs-5 mb-5">
                            <span class="text">Цена: {{ object.price }} $ </span>

                        </div>
                        <p class="lead"> Описание товара: {{ object.description }} </p>
                        <p class="lead">Дата создания карточки: {{ object.creation_date }}</p>
                        <p class="lead">Дата обновления карточки: {{ object.modification_date }}</p>

                        </ul>
                            <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                            <a href="{% url 'catalog:home' %}" class="btn btn-lg btn-block btn-outline-primary">Назад</a>
                        {% if object.owner == request.user or request.user.is_superuser %}
                            <a href="{% url 'catalog:update_product' object.pk %}" type="button" class="btn btn-lg btn-block btn-outline-primary">Редактировать</a>
                            <a href="{% url 'catalog:delete_product' object.pk%}" type="button" class="btn btn-lg btn-block btn-outline-primary">Удалить</a>
                        {% elif perms.catalog.сan_change_desc %}
                            <a href="{% url 'catalog:update_moderator' object.pk %}" type="button" class="btn btn-lg btn-block btn-outline-primary">Редактировать</a>
                        {% endif %}
                        <a href="{% url 'catalog:version' object.pk%}" type="button" class="btn btn-lg btn-block btn-outline-primary">К версиям продукта</a>
                        </div>



                    </div>
                </div>
            </div>


    </div>


{% endblock %}